[2022-06-25 19:41:34,647] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-f101_round_f.create_log_tables scheduled__2022-06-23T16:20:07.188456+00:00 [queued]>
[2022-06-25 19:41:34,683] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-f101_round_f.create_log_tables scheduled__2022-06-23T16:20:07.188456+00:00 [queued]>
[2022-06-25 19:41:34,683] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-06-25 19:41:34,683] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-06-25 19:41:34,684] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-06-25 19:41:34,811] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): create_log_tables> on 2022-06-23 16:20:07.188456+00:00
[2022-06-25 19:41:34,819] {standard_task_runner.py:52} INFO - Started process 90 to run task
[2022-06-25 19:41:34,860] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'DM-COUNT-f101_round_f', 'create_log_tables', 'scheduled__2022-06-23T16:20:07.188456+00:00', '--job-id', '1256', '--raw', '--subdir', 'DAGS_FOLDER/f_101_round_f.py', '--cfg-path', '/tmp/tmp3yodtx3t', '--error-file', '/tmp/tmpjmn84nmx']
[2022-06-25 19:41:34,872] {standard_task_runner.py:77} INFO - Job 1256: Subtask create_log_tables
[2022-06-25 19:41:35,199] {logging_mixin.py:109} INFO - Running <TaskInstance: DM-COUNT-f101_round_f.create_log_tables scheduled__2022-06-23T16:20:07.188456+00:00 [running]> on host 1a36ba6d0ffa
[2022-06-25 19:41:35,458] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DM-COUNT-f101_round_f
AIRFLOW_CTX_TASK_ID=create_log_tables
AIRFLOW_CTX_EXECUTION_DATE=2022-06-23T16:20:07.188456+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-23T16:20:07.188456+00:00
[2022-06-25 19:41:35,477] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2022-06-25 19:41:35,487] {dbapi.py:225} INFO - Running statement: CREATE SCHEMA IF NOT EXISTS logs;
CREATE SEQUENCE IF NOT EXISTS logs.seq_lg_messages INCREMENT 1 START 1;


CREATE TABLE IF NOT EXISTS logs.load_csv_to_ds (
    ID SERIAL PRIMARY KEY,
    TABLE_NAME VARCHAR(30),
    CSV_PATH TEXT,
    TIME_START_LOAD TIMESTAMP DEFAULT CURRENT_TIMESTAMP(0),
    TIME_END_LOAD TIMESTAMP,
    condition TEXT
);


CREATE TABLE IF NOT EXISTS logs.lg_messages_dm ( 	
    record_id INT,
    date_time TIMESTAMP,
    pid TEXT,
    message TEXT,
    message_type TEXT,
    usename TEXT, 
    datname TEXT, 
    client_addr TEXT, 
    application_name TEXT,
    backend_start TEXT
);, parameters: None
[2022-06-25 19:41:35,490] {postgres.py:71} INFO - NOTICE:  schema "logs" already exists, skipping

[2022-06-25 19:41:35,490] {postgres.py:71} INFO - NOTICE:  relation "seq_lg_messages" already exists, skipping

[2022-06-25 19:41:35,490] {postgres.py:71} INFO - NOTICE:  relation "load_csv_to_ds" already exists, skipping

[2022-06-25 19:41:35,490] {postgres.py:71} INFO - NOTICE:  relation "lg_messages_dm" already exists, skipping

[2022-06-25 19:41:35,539] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=DM-COUNT-f101_round_f, task_id=create_log_tables, execution_date=20220623T162007, start_date=20220625T194134, end_date=20220625T194135
[2022-06-25 19:41:35,591] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-25 19:41:35,793] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
