[2022-06-18 08:55:16,934] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.create_dm_schema_and_tables manual__2022-06-18T08:55:14.463169+00:00 [queued]>
[2022-06-18 08:55:16,951] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: DM-COUNT-account-turnover.create_dm_schema_and_tables manual__2022-06-18T08:55:14.463169+00:00 [queued]>
[2022-06-18 08:55:16,951] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 08:55:16,951] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-06-18 08:55:16,951] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 08:55:16,968] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): create_dm_schema_and_tables> on 2022-06-18 08:55:14.463169+00:00
[2022-06-18 08:55:16,973] {standard_task_runner.py:52} INFO - Started process 1711 to run task
[2022-06-18 08:55:16,977] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'DM-COUNT-account-turnover', 'create_dm_schema_and_tables', 'manual__2022-06-18T08:55:14.463169+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/dm_fill_account_turnover.py', '--cfg-path', '/tmp/tmp8taa8bri', '--error-file', '/tmp/tmp05hl0oda']
[2022-06-18 08:55:16,978] {standard_task_runner.py:77} INFO - Job 69: Subtask create_dm_schema_and_tables
[2022-06-18 08:55:17,053] {logging_mixin.py:109} INFO - Running <TaskInstance: DM-COUNT-account-turnover.create_dm_schema_and_tables manual__2022-06-18T08:55:14.463169+00:00 [running]> on host 191dd4d3d1ba
[2022-06-18 08:55:17,115] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DM-COUNT-account-turnover
AIRFLOW_CTX_TASK_ID=create_dm_schema_and_tables
AIRFLOW_CTX_EXECUTION_DATE=2022-06-18T08:55:14.463169+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-18T08:55:14.463169+00:00
[2022-06-18 08:55:17,121] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2022-06-18 08:55:17,124] {dbapi.py:225} INFO - Running statement: CREATE SCHEMA IF NOT EXISTS dm;


-- dm.dm_account_turnover_f 
CREATE TABLE IF NOT EXISTS dm.dm_account_turnover_f (
    on_date DATE,
    acount_rk NUMERIC,
    credit_amount NUMERIC(23,8),
    credit_amount_rub NUMERIC(23,8),
    debet_amount NUMERIC(23,8),
    debet_amount_rub NUMERIC(23,8)
);


-- dm.dm_f101_round_f
CREATE TABLE IF NOT EXISTS dm.dm_f101_round_f (
    FROM_DATE DATE,
    TO_DATE DATE,
    CHAPTER	VARCHAR(1),
    LEDGER_ACCOUNT VARCHAR(5),
    CHARACTERISTIC VARCHAR(1),
    BALANCE_IN_RUB NUMERIC(23,8),
    R_BALANCE_IN_RUB NUMERIC(23,8),
    BALANCE_IN_VAL NUMERIC(23,8),
    R_BALANCE_IN_VAL NUMERIC(23,8),
    BALANCE_IN_TOTAL NUMERIC(23,8),
    R_BALANCE_IN_TOTAL NUMERIC(23,8),
    TURN_DEB_RUB NUMERIC(23,8),
    R_TURN_DEB_RUB NUMERIC(23,8),
    TURN_DEB_VAL NUMERIC(23,8),
    R_TURN_DEB_VAL NUMERIC(23,8),
    TURN_DEB_TOTAL NUMERIC(23,8),
    R_TURN_DEB_TOTAL NUMERIC(23,8),
    TURN_CRE_RUB NUMERIC(23,8),
    R_TURN_CRE_RUB NUMERIC(23,8),
    TURN_CRE_VAL NUMERIC(23,8),
    R_TURN_CRE_VAL NUMERIC(23,8),
    TURN_CRE_TOTAL NUMERIC(23,8),
    R_TURN_CRE_TOTAL NUMERIC(23,8),
    BALANCE_OUT_RUB NUMERIC(23,8),
    R_BALANCE_OUT_RUB NUMERIC(23,8),
    BALANCE_OUT_VAL NUMERIC(23,8),
    R_BALANCE_OUT_VAL NUMERIC(23,8),
    BALANCE_OUT_TOTAL NUMERIC(23,8),
    R_BALANCE_OUT_TOTAL NUMERIC(23,8)
);, parameters: None
[2022-06-18 08:55:17,125] {postgres.py:71} INFO - NOTICE:  schema "dm" already exists, skipping

[2022-06-18 08:55:17,125] {postgres.py:71} INFO - NOTICE:  relation "dm_account_turnover_f" already exists, skipping

[2022-06-18 08:55:17,125] {postgres.py:71} INFO - NOTICE:  relation "dm_f101_round_f" already exists, skipping

[2022-06-18 08:55:17,134] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=DM-COUNT-account-turnover, task_id=create_dm_schema_and_tables, execution_date=20220618T085514, start_date=20220618T085516, end_date=20220618T085517
[2022-06-18 08:55:17,153] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-18 08:55:17,183] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
